#!/bin/bash
# Usage: ./populateDB -u <user> -p <password> -d <mysql_bin_directory> 
# Example: ./populateDB.sh -u gt_user -p myPassword -d /Applications/MAMP/Library/bin/
#  This script populates the glycotree DB using the mysqlimport command
#  For security reasons, YOU must supply the 
#    DB user_name, password, and directory containing mysqlimport

# The commands in this script assume it is called from glycotree/SQL/
#  Thus, files specifying the model are in the directory ../model/

start=$(date)
echo $start

cp ../model/canonical_residues.csv ./canonical_residues.csv
cp ../model/enzymes.csv ./enzymes.csv
cp ../model/enzyme_mappings.csv ./enzyme_mappings.csv
	
# glycotree/SQL/compositions.csv is generated by glycotree/build_N-tree.sh
# glycotree/SQL/correlation.csv is generated by glycotree/build_N-tree.sh


if [ $# -lt 6 ]; then
  echo "Not enough arguments"
  exit
fi

for (( i=1; i<=$#; i++)); do
  j=$(($i + 1))

  if [ ${!i} = '-u' ]; then
    user=${!j}
    echo "user name found on command line"
  fi

  if [ ${!i} = '-p' ]; then
    pw=${!j}
    echo "password found on command line"
  fi

  if [ ${!i} = '-d' ]; then
    dir=${!j}
    echo "mysql bin directory found on command line"
  fi
done


$dir/mysqlimport -u $user -p$pw --local --delete -v --fields-terminated-by="," --ignore-lines=1 --lines-terminated-by="\n" -c residue_name,residue_id,name,anomer,absolute,ring,parent_id,site,form_name,limited_to,not_found_in,notes,who,evidence,comment glycotree canonical_residues.csv 

$dir/mysqlimport -u $user -p$pw --local --delete -v --fields-terminated-by="," --ignore-lines=1 --lines-terminated-by="\n" -c type,orthology_group,uniprot,protein_refseq,dna_refseq,gene_name,gene_id,species,branch_site_specificity glycotree enzymes.csv 

$dir/mysqlimport -u $user -p$pw --local --delete -v --fields-terminated-by="," --ignore-lines=1 --lines-terminated-by="\n" -c glytoucan_ac,residue_name,residue_id,name,anomer,absolute,ring,parent_id,site,form_name,glycoct_index glycotree compositions.csv

$dir/mysqlimport -u $user -p$pw --local --delete -v --fields-terminated-by="," --ignore-lines=1 --lines-terminated-by="\n" -c glytoucan_ac,dp,homolog,relative_dp,shared glycotree correlation.csv
 
$dir/mysqlimport -u $user -p$pw --local --delete -v --fields-terminated-by="," --ignore-lines=1 --lines-terminated-by="\n" -c residue_name,residue_id,type,uniprot,requires_residue,blocked_by_residue,notes glycotree enzyme_mappings.csv
